### ISSUE TITLE
Public data directory for modules database

### ISSUE THREAD

**Issue by Luiz-N** [rjrudin/ml-gradle#105]
@rjrudin I would like to set a unique public data-directory for the modules database forests of an application created by gradle. I have achieved this with the content database by adding a "data-directory" property to the content-forest.json config file but cannot seem to get it working for the auto created modules db.

I have tried adding the following code to my build.gradle:

`def modulesForestCommand = new com.marklogic.appdeployer.command.forests.DeployForestsCommand()
  modulesForestCommand.setDatabaseName(mlAppName + "-modules")
  modulesForestCommand.setForestFilename("modules-forest.json")
  mlAppDeployer.commands.add(modulesForestCommand)`

In modules-forest.json I have the same tokens as my content-forest.json file and if a modules DB already exists this will work in the sense that new forests will be created in my specified data-directory.  On a fresh deploy however the build fails with an error complaining that the modules-db does not exist...  Is there a way to attach this forest file to the modules db while it's being created or perhaps another workaround?

**Comment by rjrudin** [comment]
@Luiz-N It's failing on a fresh deploy because DeployForestsCommand has a sort order before that of DeployRestApiServersCommand. The call fails because the modules database hasn't been created yet. 

The best way around this is to add a config file for the modules database that DeployRestApiServersCommand would otherwise create for you. You can then configure the forests for that database. And when DeployRestApiServersCommand runs, it will see that the modules database already exists and won't create a new one.

Note that in version 2.2.0 of ml-gradle, you can add any database config file that you want to ml-config/databases, and it will automatically be deployed. This wasn't the case in previous versions. I think a modules-database.json file should do the trick.

**Comment by Luiz-N** [comment]
yes!
This worked great...
`def moduleDBCommand = new com.marklogic.appdeployer.command.databases.DeployDatabaseCommand("modules-database.json")
  moduleDBCommand.setForestFilename("modules-forest.json")
  moduleDBCommand.setCreateForestsOnEachHost(false)
  mlAppDeployer.commands.add(moduleDBCommand)`

to recreate a modules database with custom forests config. Thanks!
