### ISSUE TITLE
passed in property for mlcp task

### ISSUE THREAD

**Issue by Luiz-N** [rjrudin/ml-gradle#106]
@rjrudin  I have a task of type MlcpTask that uses an options file to import some data. I would like to allow for a user to pass in a string for the path of that options file which can then be checked via project.hasProperty(). The problem is that if this property is not passed in then any gradle task (such as mlDeploy) will fail... the doLast {} block does not seem to fix this... Any ideas?

**Comment by rjrudin** [comment]
Try using the args property of JavaExec to specify an options file instead. I haven't tried this yet, but I think you can do something like this (pseudo-code):

    ext {
       if optionsFile property is set, then importArgs = ["-options_file", optionsFile]
       else importArgs = ["... other args ..."]
    }

    task import(type: com.marklogic.gradle.task.MlcpTask) {
      args = importArgs
    }

The idea is you construct the args array based on the conditional of whether a project property is set. Gradle will otherwise complain if you use a property and it's not set anywhere.

**Comment by Luiz-N** [comment]
Thanks again @rjrudin... putting this code in a ext block worked...

```
importArgs = null
if (project.hasProperty("optionsFile")) {
  importArgs = [options_file: project.property("optionsFile")]
}
```

then later in my task I throw an error if (!importArgs)
