### ISSUE TITLE
DeployAmps only checks local name

### ISSUE THREAD

**Issue by sparnell** [rjrudin/ml-gradle#130]
mlDeployAmps fails if an Amp with the same local name already exists. It does not distinguish between functions with the same local name but different namespaces.

**Comment by rjrudin** [comment]
Hey @sparnell - I wrote up a bug for this a while back - https://github.com/rjrudin/ml-app-deployer/issues/60 . It required a fix in the Management REST API, and I don't know if that's been fixed or not. It's been an issue on one project of mine since we switched to the REST API - I'll try to check out the latest version of ML 8.0-5.x and see if it's fixed there.

**Comment by rjrudin** [comment]
Adding this to 2.4.0, assuming there's a fix in the Mgmt REST API for it.

**Comment by sparnell** [comment]
sorry - missed that you'd already noted this issue. I haven't tested this extensively, but in v8 amps with conflicting local names can be installed calling the management endpoint using something like curl. Is the issue that you get the wrong answer if you ask the endpoint if the amp is already configured?

**Comment by rjrudin** [comment]
Yes - at least on 8.0-4, when a GET request is sent to find the amp, it's never found, because the modules database is listed as the filesystem.

I'm on 8.0-5.8, and it appears to be fine. I'm going to test it out some more and try to close this out.

**Comment by rjrudin** [comment]
@sparnell Here's the PR in ml-app-deployer for the fix - it at least works now on 8.0-5.8. I had to change the "save" method for an amp so that existence is based on local-name, modules-database, namespace, and document-uri. 

I hope to have 2.4.0 out by the end of next week - there's some qconsole-related stuff I hope to have wrapped up by then.

**Comment by rjrudin** [comment]
This will be fixed in 2.4.0 via a fix in the latest version of ml-app-deployer
