### ISSUE TITLE
Prompt for authentication credentials 

### ISSUE THREAD

**Issue by jmakeig** [rjrudin/ml-gradle#133]
As a developer, I want to be able to package up a deployment script that is as generally applicable as possible in order to reduce the steps it takes for a user to get started. In particular, the credentials for the user bootstrapping a deployment is not generalizable. In the past we've shipped scripts that default to `admin`:`admin`. However, that encourages poor security practices in the service of expediency. ml-gradle should prompt a user for a username and password when they are known to be running from an interactive environment. Something [like](https://www.timroes.de/2014/01/19/using-password-prompts-with-gradle-build-files/) might do the trick.

**Comment by grechaw** [comment]
I can do this as part of example build too, I don't think it has to be part of ml-gradle

**Comment by jmakeig** [comment]
> I can do this as part of example build too, I don't think it has to be part of ml-gradle

Doesn’t have to, but I’d prefer it to be an option in ml-gradle, rather than having to have each project re-invent it.

**Comment by rjrudin** [comment]
@jmakeig You mention "known to be running from an interactive environment". What do you mean by that?

I think this is tricky, because Gradle code - whether it's in ml-gradle or in build.gradle - can do a few things:

1. If mlPassword is not set, ask for it
1. If mlPassword is set, bounce it against a known endpoint in ML (8000/v1/eval?) to verify that it works. If it fails, ask for it.
1. If mlPassword is set, assume it's valid and proceed

The problem though is the user will have to do this every time a Gradle task is run. It seems far better for the user to override the password once. Gradle has many options for doing that, such as the properties plugin. 

I know there's less friction if the user doesn't have to modify a file when they're first trying out e.g. entity services, but I think it's reasonable to tell the user to set their password - either by overriding gradle.properties or application.properties, or by overriding a file known by the properties plugin, or simply putting "-DmlPassword=durantshouldhavegonetotheceltics" on the command line.

**Comment by grechaw** [comment]
`or simply putting "-DmlPassword=durantshouldhavegonetotheceltics" on the command line. `

+1 to that.  We should distinguish between casual users and professionals.  To anyone who would actually use the feature, this is sufficient and a better solution wrt console access.  We can document it tough front-and-center in the readme (using -D this way, or would it be -P @rjrudin)

**Comment by jmakeig** [comment]
> “known to be running from an interactive environment”

There are scenarios where `System.console()` is not available, like in an IDE or CI environment. This feature is not meant to address those scenarios. I’m specifically talking about Day 0, typing

```shell
git clone …
cd my_proj
./gradlew         # Or some other one-line, zero-option bootstrapper

> Admin user:
admin
> Admin password:
********
…
```

I think the linked solution would have the same effect as `-DmlPassword=durantshouldhavegonetotheceltics` without having to feel yucky about typing your password in clear text. An init script could also write the appropriate properties file with the entered credentials.

**Comment by rjrudin** [comment]
Sorry, I mean "-P", not "-D". Was too focused on Durant.

Gradle has a variety of options for an init script - https://docs.gradle.org/current/userguide/init_scripts.html . I think ~/.gradle/init.gradle is a pretty simple option, and I think a lot of developers are used to this convention of a "~/(name of product)/(some init config file)" configuration file.

**Comment by jmakeig** [comment]
> Was too focused on Durant.

@rjrudin You and the entire NBA backcourt.

**Comment by rjrudin** [comment]
@jmakeig and @grechaw - do you still want something here? I feel like having @grechaw add something specifically for the project in question makes more sense, as the vast majority of the time with a build tool like ml-gradle, it's being used on a project with developers that either have a default admin password or are using a Gradle init script or the properties plugin to override the default admin password. 

My thought is @grechaw could add something for the project in question, and that could then be rolled into ml-gradle via a PR, where ml-gradle would use the console to ask for mlPassword if that property isn't defined yet.

**Comment by grechaw** [comment]
I agree with you @rjrudin .
