### ISSUE TITLE
MlcpTask - not all operation use -host or -port

### ISSUE THREAD

**Issue by sparnell** [rjrudin/ml-gradle#149]
Example:

COPY requires input_host, input_port, output_host, output_port. 
MLCP throws an exception if -host and/or -port are passed. MlcpTask.groovy adds both -host and -port if they're not provided.

**Comment by rjrudin** [comment]
Thanks @sparnell , I ran into this recently myself. I was initially thinking that for a COPY, it would be easier to just use JavaExec instead of MlcpTask, as all of the things that MlcpTask eagerly sets don't apply to a COPY. But I think it's nice to still have the inputs expressed as Gradle params. So I think a good solution here is - if the command is "COPY", then don't eagerly add any inputs, expect the user to set all the input_ and output_ params - which the user can still do via Gradle task params. Sound good?

**Comment by sparnell** [comment]
yes, sounds good to me.
