### ISSUE TITLE
Make it easy to configure the timestamps file used by e.g. mlWatch

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/ml-gradle#163]
Main reason is so it can be tossed in a directory that IntelliJ can ignore.

**Comment by hansenmc** [comment]
It also might be useful if you are deploying to a variety of environments and want to have different timestamp files for each environment.

If there were a property that could be set in each env file, and/or overridden on the commandline to control the temp file location makes it easier to be able to switch from running against localhost to other dev environments without clearing the timestamp file or (re)touching files that have already been pushed to the previous mlWatch environment in order to get them pushed to the next environment.

**Comment by rjrudin** [comment]
Turns out this already existed - documented at https://github.com/rjrudin/ml-gradle/wiki/Property-reference

**Comment by hansenmc** [comment]
It has been a source of confusion on our project that when switching between environments, the `mlModuleTimestampsPath` was the default, and files were not being pushed to the subsequent environments.

It might be a good idea to set that property in some of the examples projects env files, in order to demonstrate that it can be done and might might even be a best practice, in order to ensure that changes are recognized for the applied environment.

**Comment by rjrudin** [comment]
@hansenmc that's interesting, I've taken advantage of this in a different way on one project - when I want to hotfix a shared development environment, I like that I can fire up mlWatch and not have it load any modules except the one(s) I'm about to modify as part of the hotfix. 

I think your suggestion though is - provide some documentation on how to adjust this property based on an environment so that people are aware of a solution?

**Comment by hansenmc** [comment]
Yes, I think better documentation might help. 

Also, it appears that the mlDeleteModulesTimestamp task [will always delete the default file](https://github.com/rjrudin/ml-gradle/blob/625e3aaadeb58dfa9f04046a31234b33724b4134/src/main/groovy/com/marklogic/gradle/task/DeleteModuleTimestampsFileTask.groovy#L10), and won't use the custom `mlModulesTimestampPath` value. It doesn't have any logic to read the currently configured `mlModuleTimestampsPath` from the AppConfig.

If I run the following command:

    gradle mlwatch -PmlModuleTimestampsPath="build/custom.properties"

I see that `build/custom.properties` exists and is populated with a list of my files and timestamps.

Then I run:

    gradle mlDeleteModuleTimestampsFile -PmlModuleTimestampsPath="build/custom.properties"

and the `build/custom.properties` is not deleted. If there were a `build/ml-last-configured-timestamps.properties` when executed with the custom value, the default `build/ml-last-configured-timestamps.properties` file is deleted.
