### ISSUE TITLE
Document Test Configuration

### ISSUE THREAD

**Issue by RobertSzkutak** [rjrudin/ml-gradle#173]
Many Roxy users have both a test-content-database and a test-modules-database for running unit tests on their code.

Roxy users may:

* Deploy unit tests only to the test-modules-database
* Have an appserver configured just for running unit tests on the test-content and test-modules DB
* Not deploy any unit test code or testing infrastructure to higher level environments (PROD)

I get the sense that most if not all of this is probably possible with Gradle but documentation or a good tutorial is desperately needed.

**Comment by sastafford** [comment]
https://github.com/rjrudin/ml-gradle/wiki/Setup-Test-Resources

Most of the testing executed with this project have been via Java and JUnit testing, since Gradle makes it simple to run regression tests.  The ml-gradle component will setup the testing infrastructure necessary to run these types of tests.  

Recommend to open up a more specific issue to support any type of XQuery based unit testing (i.e. not writing out test code to a modules database)

**Comment by RobertSzkutak** [comment]
Thanks for documenting that.

Not sure if you're aware of this but you can run XRay unit tests with a JUnit response. Could that be integrated into the JUnit testing already in place?
