### ISSUE TITLE
Metadata for ml-config resources

### ISSUE THREAD

**Issue by RobertSzkutak** [rjrudin/ml-gradle#176]
I think the JSON structure needs to be modified for ml-config resources to support metadata useful to ml-gradle.

For example:

`{
  "metadata" : {}
  "object" : {}
}`

Where object is the JSON sent to the Management API and metadata can do things like specify which environments the resource should/should not be deployed to or whether the resource is deprecated (it should only be wiped if it exists and never deployed)

**Comment by rjrudin** [comment]
This gets tricky. With one exception (configuring many forests in a single file), every payload supported by ml-gradle conforms to what the Manage API expects. That means I don't have to document anything for those payloads - just read the existing Manage API docs, or better yet, create the resource manually via the Admin API and then copy it from host:8002. 

Additionally, an XML structure would need to be supported too. XML has at least one benefit over JSON - you can insert comments to explain why something is configured a certain way. 

I talked with someone about a ".metadata" file in a directory that could be used to specify the things you mention. I think that's probably the better approach. It's one level of indirection - gotta look at .metadata instead of the payload file itself - but I think it's better overall if the payload files only contain the payload and nothing more.

Note too that there's a way to ignore filenames already, which can be controlled via an environment property.

I'm going to close this, but the need for it may arise as more "metadata" needs to be specified about particular resource files.
