### ISSUE TITLE
ml-gradle init messages should be quiet if not running ml-gradle

### ISSUE THREAD

**Issue by xquery** [rjrudin/ml-gradle#19]
when not running an ml-gradle task, consider suppressing gradle init messages.

example of console trace;
```
Initializing ml-gradle
App name: quick-start
App host: localhost
App username: admin
App REST port: 8200
Manage host: localhost
Manage username: admin
Admin host: localhost
Admin username: admin
Initializing ManageClient with manage config of: [host: localhost, port: 8002, username: admin]
Initialized ManageClient with base URL of: http://localhost:8002
Finished initializing ml-gradle
```

**Comment by rjrudin** [comment]
I found that within MarkLogicPlugin, I can call project.gradle.startParameters and get a list of requested task names. I can then do something like "If a task starts with ml, then print out the ml-gradle init stuff."

Alternatively, I can log this at the INFO level instead of using println in MarkLogicPlugin, which writes to sysout. Gradle doesn't show INFO logging by default - you have to do "gradle -i" or "gradle --i". 

I think I like the idea of logging it at the INFO level - it gives the user control. Sound good?

**Comment by xquery** [comment]
I think the either solution is suitable.
