### ISSUE TITLE
rationalise targets

### ISSUE THREAD

**Issue by xquery** [rjrudin/ml-gradle#20]
careful target naming in gradle reduces cognitive load.

for example the current list of targets are ;

mlAppDeploy
mlAppUndeploy
mlClearContentDatabase
mlClearModules
mlCpfDeploy
mlCpfLoadDefaultPipelines
mlCreateResource
mlCreateTransform
mlDeleteModuleTimestampsFile
mlDeploy
mlInit
mlInstallAdmin
mlLoadModules
mlPostDeploy
mlPostUndeploy
mlPrepareRestApiDependencies
mlReloadModules
mlScaffold
mlUndeploy
mlUpdateContentDatabase
mlUpdateRestApiServers
mlWatch

I would suggest rationalising this list and thinking about overlap between targets.

**Comment by rjrudin** [comment]
In general, I've chosen a syntax of "ml(verb)(noun)" - e.g. mlClearModules, mlReloadModules. 

The reason I have tasks like "mlAppDeploy" and "mlCpfDeploy" - i.e. "ml(noun)(verb)" - is that if I use e.g. "mlDeployCpf", then a user can't shorten "mlDeploy" to something like "mldep", which Gradle will then figure out must be "mlDeploy". But that may not really matter. It's convenient when a verb is really long, but there aren't many such verbs. 

So do you think it would suffice if all tasks fit the "ml(verb)(noun)" pattern? I think that would make things intuitive for the user - the user then just has to learn the verbs and nouns that matter to ml-gradle.

There's then the issue of "mlPostDeploy", but I think it would be intuitive if there's a set of "mlPost(verb)" tasks which gives the user an easy way of tacking more tasks onto the end of an existing task. We don't need "mlPre(verb)" tasks because Gradle handles that via "dependsOn".

**Comment by xquery** [comment]
I was more thinking more of having a single verb ex. 'mlDeploy' which would deploy everything then you would exclude (via commandline switches and/or properties). I am fine with the current naming convention perse.

Don't let me distract you, I am all for specific targets as you have them ... just thinking control via properties/commandline switches of nouns maybe worth investigating.

**Comment by rjrudin** [comment]
Okay, so e.g. instead of mlCpfDeploy, "gradle mlDeploy -Pfeature=cpf"?

**Comment by xquery** [comment]
maybe ... I wonder how that might translate in terms of a set of java properties eg.

```
  feature=cpf
```

resources might also be represented

```
  database=MyModuleDB,MyContentDb
```

admittedly, this is tinkering around the edges, but thought I would mention it.

**Comment by rjrudin** [comment]
Jim, I'm going to close this - I did standardize the naming a while back for tasks to start with "mlDeploy" in general, and they're better grouped when you run "gradle tasks" as well.
