### ISSUE TITLE
Execute roxy commands that will run a ml-gradle task

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#6]
As a developer used to roxy commands
I want to use TITLE
So that I decrease my learning curve to using ml-gradle

This is a low priority nice-to-have feature.  If we want to get serious about our consultants using ml-gradle this might prove to be a nice way to transition.

**Comment by rjrudin** [comment]
I think with ml-gradle 2, a user only really needs to know two commands - mldeploy and mlloadmodules. And mldeploy does what "ml (env) bootstrap" and "ml (env) deploy modules" both do, so adding in a "bootstrap" task would muddy the waters a bit to me - especially since I think "configure" is the more appropriate verb.
