### ISSUE TITLE
How to load library modules from mlLoadModules

### ISSUE THREAD

**Issue by rlouapre** [rjrudin/ml-gradle#60]
First time using ```ml-gradle```
I cloned ```ml-camel-client``` and I tried to follow the wiki [1] to load a simple module library.
I have a test.xqy module stored in src/main/ml-modules
I run: ```gradle -i mlLoadModules```
Here is the end of the console output:
```
A dependent class, javax/mail/MessagingException, of the component class com.sun.jersey.core.impl.provider.entity.MimeMultipartProvider is not found. The component is ignored.
Loading modules from dir: src/main/ml-modules
Initializing XCC session; host: ml8.local; username: admin; database name: camel-sandbox-modules
Closing XCC session
:mlLoadModules (Thread[main,5,main]) completed. Took 0.841 secs.

BUILD SUCCESSFUL

Total time: 9.699 secs
Stopped 0 compiler daemon(s).
```

But the module has not been loaded in the modules database.

[1] - https://github.com/rjrudin/ml-gradle/wiki/How-modules-are-loaded

**Comment by rjrudin** [comment]
Is test.xqy directly under src/main/ml-modules? It won't be loaded from there - you need to put it under one of the directories defined at https://github.com/rjrudin/ml-gradle/wiki/How-modules-are-loaded so that ml-gradle knows what kind of a REST API module it is - library/asset, service, transform, etc. It sounds like it should be under "/ext" - thus "src/main/ml-modules/ext/test.xqy".

**Comment by rlouapre** [comment]
I moved it in /src/main/ml-modules/ext. It worked.
