### ISSUE TITLE
Keep mlWatch running in the face of errors

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-gradle#65]
mlWatch dies when there are errors in deploying. Often these errors are a result of my fat-fingering some code.

I'd prefer for mlWatch to spit out the error, but continue watching. As-is I have to restart it.

**Comment by rjrudin** [comment]
Hey  Paxton - I remember looking into this maybe a year ago. I think the problem I ran into was that mlWatch would need to be smart enough to still update the "last loaded timestamp" for the module, even though it failed to load. That way, mlWatch wouldn't keep trying to load the module with the error in it, only to have it fail over and over. 

I'll try to look into this again this week. I agree it's an issue, though I've not been affected by it much on my main project because we do very little with /v1/resources and /v1/transforms.

**Comment by rjrudin** [comment]
ml-javaclient-util has support for this - the DefaultModulesLoader class has a "boolean catchExceptions" property. 

I think it's good to default to failing on an exception during a normal deployment. If there's a bug in a resource/transform, the deploy should fail. But during mlWatch, exceptions should be caught. So I'll just modify WatchTask in ml-gradle.

I'll put together a Wiki page in here about how to test ml-gradle changes, which I usually do via the sample-project or a similar project in ./examples.

**Comment by rjrudin** [comment]
Doh, I forgot to include this in 2.0rc4. It'll be in 2.0 final for sure, which I hope to do today or in a couple days.

**Comment by rjrudin** [comment]
In 2.0rc5
